# Generated by Django 5.1.7 on 2025-03-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_acte', models.CharField(max_length=50, unique=True, verbose_name="Code de l'acte")),
                ('total_acte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant total de l'acte")),
                ('total_tiers_payant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant pris en charge par le tiers payant')),
                ('reste_paye_cps', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Reste à payer CPS')),
            ],
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(max_length=7, verbose_name='DN (numéro à 7 chiffres)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du patient')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom du patient')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('numero_facture', models.CharField(max_length=50, verbose_name='Numéro de facture')),
                ('date_acte', models.DateField(verbose_name="Date de l'acte")),
                ('date_facture', models.DateField(verbose_name='Date de la facture')),
                ('regime', models.CharField(choices=[('ss', 'Sécurité Sociale'), ('rns', 'RNS'), ('salarie', 'Salarié'), ('rst', 'RST')], max_length=20, verbose_name='Régime')),
                ('regime_lm', models.BooleanField(default=False, verbose_name='Régime LM (oui/non)')),
                ('droit_ouvert', models.BooleanField(default=False, verbose_name='Droit ouvert (oui/non)')),
                ('lieu_acte', models.CharField(choices=[('cabinet', 'Cabinet'), ('clinique', 'Clinique')], max_length=50, verbose_name="Lieu de l'acte")),
                ('total_acte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant total de l'acte (facturé)")),
                ('tiers_payant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant tiers payant')),
                ('total_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total payé')),
                ('statut_dossier', models.CharField(choices=[('ras', 'RAS'), ('dno', 'DNO'), ('dnolm', 'DNOLM'), ('impaye', 'Impayé'), ('rejet', 'Rejet')], max_length=20, verbose_name='Statut du dossier')),
                ('numero_rejet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de rejet')),
                ('numero_bordereau', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de bordereau')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('code_acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturations', to='comptabilite.code', verbose_name="Code de l'acte")),
            ],
        ),
    ]
