# Generated by Django 5.1.7 on 2025-03-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medecin', models.CharField(max_length=100, verbose_name='Nom du Médecin')),
                ('code_m', models.CharField(max_length=50, verbose_name='Code M')),
                ('nom_clinique', models.CharField(max_length=100, verbose_name='Nom de la Clinique')),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='code_reel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code réel'),
        ),
        migrations.AddField(
            model_name='code',
            name='longue_maladie',
            field=models.BooleanField(default=False, verbose_name='Longue maladie'),
        ),
        migrations.AddField(
            model_name='code',
            name='parcours_soin',
            field=models.BooleanField(default=False, verbose_name='Parcours de soin'),
        ),
        migrations.AddField(
            model_name='code',
            name='variable_1',
            field=models.CharField(blank=True, help_text='Vide ou 1', max_length=1, null=True, verbose_name='Variable 1'),
        ),
        migrations.AddField(
            model_name='code',
            name='nom_medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.medecin', verbose_name='Médecin'),
        ),
    ]
