# Generated by Django 5.1.7 on 2025-03-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_medecin_code_code_reel_code_longue_maladie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='nom_medecin',
            new_name='medecin',
        ),
        migrations.RemoveField(
            model_name='code',
            name='reste_paye_cps',
        ),
        migrations.RemoveField(
            model_name='code',
            name='total_tiers_payant',
        ),
        migrations.AddField(
            model_name='code',
            name='code_acte_normal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code Acte Normal'),
        ),
        migrations.AddField(
            model_name='code',
            name='modificateur',
            field=models.CharField(blank=True, help_text='CS ou vide', max_length=2, null=True, verbose_name='Modificateur'),
        ),
        migrations.AddField(
            model_name='code',
            name='tiers_payant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tiers payant'),
        ),
        migrations.AddField(
            model_name='code',
            name='total_paye',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total payé'),
        ),
        migrations.AddField(
            model_name='code',
            name='variable_2',
            field=models.CharField(blank=True, help_text='Vide ou 1', max_length=1, null=True, verbose_name='Variable 2'),
        ),
        migrations.AlterField(
            model_name='facturation',
            name='tiers_payant',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant tiers payant'),
        ),
        migrations.AlterField(
            model_name='facturation',
            name='total_acte',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Montant total de l'acte (facturé)"),
        ),
        migrations.AlterField(
            model_name='facturation',
            name='total_paye',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Total payé'),
        ),
    ]
