# Generated by Django 5.1.7 on 2025-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_rename_nom_medecin_code_medecin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='date_bordereau',
            field=models.DateField(blank=True, null=True, verbose_name='Date du bordereau'),
        ),
        migrations.AlterField(
            model_name='code',
            name='tiers_payant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Tiers payant'),
        ),
        migrations.AlterField(
            model_name='code',
            name='total_acte',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Montant total de l'acte"),
        ),
        migrations.AlterField(
            model_name='code',
            name='total_paye',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total payé'),
        ),
    ]
