# Generated by Django 5.2 on 2025-04-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_facturation_date_bordereau_alter_code_tiers_payant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='tiers_payant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tiers payant'),
        ),
        migrations.AlterField(
            model_name='code',
            name='total_acte',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant total de l'acte"),
        ),
        migrations.AlterField(
            model_name='code',
            name='total_paye',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total payé'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('modalite_paiement', models.CharField(choices=[('CB', 'Carte Bancaire'), ('Chèque', 'Chèque'), ('Liquide', 'Liquide'), ('Virement', 'Virement'), ('Gratuit', 'Gratuit')], max_length=20, verbose_name='Modalité de paiement')),
                ('banque', models.CharField(choices=[('Banque de Tahiti', 'Banque de Tahiti'), ('Socredo', 'Socredo'), ('Banque de Polynésie', 'Banque de Polynésie')], max_length=50, verbose_name='Banque')),
                ('porteur', models.CharField(max_length=100, verbose_name='Porteur')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant')),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='comptabilite.facturation')),
            ],
        ),
    ]
