# Generated by Django 5.2 on 2025-04-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_alter_code_tiers_payant_alter_code_total_acte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='liste',
            field=models.BooleanField(default=False, help_text='Coché quand ce chèque a été listé', verbose_name='Listé'),
        ),
        migrations.AlterField(
            model_name='code',
            name='modificateur',
            field=models.CharField(blank=True, help_text='CS, APC ou vide', max_length=3, null=True, verbose_name='Modificateur'),
        ),
        migrations.AlterField(
            model_name='code',
            name='total_acte',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Montant total de l'acte"),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='banque',
            field=models.CharField(choices=[('Banque de Tahiti', 'Banque de Tahiti'), ('Socredo', 'Socredo'), ('Banque de Polynésie', 'Banque de Polynésie'), ('CC°', 'CCP')], max_length=50, verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Montant'),
        ),
    ]
