# Generated by Django 5.2 on 2025-04-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_paiement_liste_alter_code_modificateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='parcours_soin',
            field=models.BooleanField(default=False, verbose_name='Parcours de soins'),
        ),
        migrations.AlterField(
            model_name='code',
            name='tiers_payant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Montant tiers payant'),
        ),
        migrations.AlterField(
            model_name='code',
            name='total_paye',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Total payé'),
        ),
        migrations.AlterField(
            model_name='facturation',
            name='droit_ouvert',
            field=models.BooleanField(default=False, verbose_name='Droits ouverts : (oui/non)'),
        ),
        migrations.AlterField(
            model_name='facturation',
            name='tiers_payant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Montant tiers payant'),
        ),
        migrations.AlterField(
            model_name='facturation',
            name='total_paye',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Total payé'),
        ),
    ]
