# Generated by Django 5.2 on 2025-04-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_alter_code_parcours_soin_alter_code_tiers_payant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de facture'),
        ),
    ]
