# Generated by Django 5.2 on 2025-04-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0009_alter_facturation_code_acte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='total_acte',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name="Montant total de l'acte (facturé)"),
        ),
    ]
