# Generated by Django 5.2 on 2025-05-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0011_facturation_regime_tp_alter_facturation_lieu_acte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='banque',
            field=models.CharField(choices=[('Banque de Tahiti', 'Banque de Tahiti'), ('Socredo', 'Socredo'), ('Banque de Polynésie', 'Banque de Polynésie'), ('CCP', 'CCP')], max_length=50, verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='modalite_paiement',
            field=models.CharField(choices=[('-----', '-----'), ('CB', 'Carte Bancaire'), ('Chèque', 'Chèque'), ('Liquide', 'Liquide'), ('Virement', 'Virement'), ('Gratuit', 'Gratuit')], max_length=20, verbose_name='Modalité de paiement'),
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mois (1-12)')),
                ('total_acte_cabinet', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total des actes au Cabinet')),
                ('total_acte_clinique', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total des actes en Clinique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Statistique mensuelle',
                'verbose_name_plural': 'Statistiques mensuelles',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
