# Generated by Django 5.2 on 2025-05-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0012_alter_paiement_banque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisionHospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_bloc', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('motif_hospitalisation', models.CharField(max_length=255)),
                ('lieu_hospitalisation', models.CharField(choices=[('Médecine', 'Médecine'), ('Bloc', 'Bloc'), ('Soins Intensifs', 'Soins Intensifs')], max_length=50)),
                ('cs_anesthesie', models.BooleanField(default=False)),
                ('fo_ag', models.BooleanField(default=False)),
                ('colo_ag', models.BooleanField(default=False)),
                ('fo_al', models.BooleanField(default=False)),
                ('colo_al', models.BooleanField(default=False)),
                ('eeh_ag', models.BooleanField(default=False)),
                ('eeb_al', models.BooleanField(default=False)),
                ('cs_cardiologie', models.BooleanField(default=False)),
                ('cs_pneumologie', models.BooleanField(default=False)),
                ('cs_dermatologie', models.BooleanField(default=False)),
                ('courrier', models.TextField(blank=True)),
                ('remarque', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='facturation',
            name='lieu_acte',
            field=models.CharField(choices=[('Cabinet', 'Cabinet'), ('Clinique', 'Clinique')], default='Cabinet', max_length=50, verbose_name="Lieu de l'acte"),
        ),
        migrations.AlterField(
            model_name='facturation',
            name='statut_dossier',
            field=models.CharField(choices=[('RAS', 'RAS'), ('DNO', 'DNO'), ('DNOLM', 'DNOLM'), ('Impayé', 'Impayé'), ('Rejet', 'Rejet')], default='RAS', max_length=20, verbose_name='Statut du dossier'),
        ),
    ]
