# Generated by Django 5.2 on 2025-05-16 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0013_previsionhospitalisation_alter_facturation_lieu_acte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='colo_ag',
            field=models.BooleanField(default=False, verbose_name='Coloscopie / AG'),
        ),
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='colo_al',
            field=models.BooleanField(default=False, verbose_name='Coloscopie sans AG'),
        ),
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='cs_anesthesie',
            field=models.BooleanField(default=False, verbose_name='Consultation anesthésie'),
        ),
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='cs_cardiologie',
            field=models.BooleanField(default=False, verbose_name='Consultation cardiologie'),
        ),
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='cs_dermatologie',
            field=models.BooleanField(default=False, verbose_name='Consultation dermatologie'),
        ),
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='cs_pneumologie',
            field=models.BooleanField(default=False, verbose_name='Consultation pneumologie'),
        ),
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='eeb_al',
            field=models.BooleanField(default=False, verbose_name='Echo-Endoscopie basse sans AG'),
        ),
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='eeh_ag',
            field=models.BooleanField(default=False, verbose_name='Echo-Endoscopie Haute / AG'),
        ),
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='fo_ag',
            field=models.BooleanField(default=False, verbose_name='FOGD / AG'),
        ),
        migrations.AlterField(
            model_name='previsionhospitalisation',
            name='fo_al',
            field=models.BooleanField(default=False, verbose_name='FOGD sans AG'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
