# Generated by Django 5.2 on 2025-05-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0015_message_lu_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prochain_numero', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
