# Generated by Django 5.2 on 2025-10-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0016_parametragefacturation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(db_index=True, max_length=7, verbose_name='DN')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_observation', models.DateField(auto_now_add=True, verbose_name="Date de l'observation")),
                ('motif_consultation', models.CharField(max_length=255, verbose_name='Motif de consultation')),
                ('texte_observation', models.TextField(verbose_name='Observation')),
                ('conclusion_observation', models.TextField(blank=True, verbose_name='Conclusion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_observation', '-created_at'],
                'indexes': [models.Index(fields=['dn', 'date_observation'], name='comptabilit_dn_361555_idx')],
            },
        ),
    ]
