# Generated by Django 5.2 on 2025-11-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0018_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(db_index=True, max_length=7, verbose_name='DN')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('type_courrier', models.CharField(choices=[('FOGD', 'Fibroscopie gastrique'), ('COLO', 'Coloscopie'), ('ECHO', 'Échographie abdominale'), ('SYN', 'Courrier de synthèse')], max_length=5, verbose_name='Type de courrier')),
                ('date_courrier', models.DateField(auto_now_add=True, verbose_name='Date du courrier')),
                ('corps', models.TextField(verbose_name='Texte du courrier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_courrier', '-created_at'],
                'indexes': [models.Index(fields=['dn', 'date_courrier'], name='comptabilit_dn_6a2ed7_idx')],
            },
        ),
    ]
