# Generated by Django 5.2 on 2025-11-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0019_courrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='type_courrier',
            field=models.CharField(choices=[('FOGD', 'Fibroscopie gastrique'), ('COLO', 'Coloscopie'), ('ECHO', 'Échographie abdominale'), ('SYN', 'Courrier de synthèse'), ('CONS', 'Fiche de consentement éclairé'), ('ATRE', 'Attestation de retour')], max_length=5, verbose_name='Type de courrier'),
        ),
        migrations.CreateModel(
            name='BiopsyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(db_index=True, max_length=7, verbose_name='DN')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('type_examen', models.CharField(choices=[('FOGD', 'Fibroscopie gastrique'), ('COLO', 'Coloscopie')], max_length=4)),
                ('destination', models.CharField(choices=[('CERBA', 'CERBA - France'), ('CHT', 'Service anatomo-pathologie - CHT')], max_length=10)),
                ('exam_date', models.DateField()),
                ('send_on', models.DateField(db_index=True, help_text="Date prévue d'envoi du rappel")),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-send_on', '-created_at'],
                'indexes': [models.Index(fields=['dn', 'send_on', 'sent'], name='comptabilit_dn_f21bec_idx')],
            },
        ),
    ]
