# Generated by Django 5.2 on 2025-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0023_bibliographie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondantEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=255, verbose_name='Adresse e-mail')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Correspondant',
                'verbose_name_plural': 'Correspondants',
                'ordering': ['name', 'email'],
                'indexes': [models.Index(fields=['name'], name='comptabilit_name_9b05d6_idx'), models.Index(fields=['email'], name='comptabilit_email_7908ee_idx')],
                'unique_together': {('name', 'email')},
            },
        ),
    ]
